### ISSUE TITLE
How to add admin permission?

### ISSUE THREAD

**Issue by denrio157** [Hackmastr/css-basic-admin#11]
![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/84ea008e-ced0-4927-852d-c74a34a243f5)
![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/eda18da4-9952-4ce0-91ce-1ecf5f0af590)

**Comment by Hackmastr** [comment]
Hello, 

This plugin uses the core admin framework. 
You can see how it works here: https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

**Comment by denrio157** [comment]
> Hello,
> 
> This plugin uses the core admin framework. You can see how it works here: https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

Awww its working, btw why when i'm gonna change MAP still crash server like this? and my server going to offline after this
![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/7c89f742-ff83-47bf-80d9-0a83e02b6ee4)

**Comment by Hackmastr** [comment]
Were you using the map command when it crashed?

**Comment by denrio157** [comment]
> Were you using the map command when it crashed?

In-game and when I'm execute my config i have warning this 
♠[BasicAdmin]☺ Error loading database.
![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/92ded952-68e4-490e-a0c7-fa5c43029c6d)

**Comment by denrio157** [comment]
![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/7f2c86ab-409d-4709-a4b9-0696599725ab)

**Comment by denrio157** [comment]
> Were you using the map command when it crashed?

So... When i talk to my friend to join my server, and he shoot this console send me this
I mean shoot with his gun

**Comment by denrio157** [comment]
![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/8c48799c-03b2-4b77-a694-bf169d0987fa)

**Comment by Hackmastr** [comment]
> > Were you using the map command when it crashed?
> 
> In-game and when I'm execute my config i have warning this ♠[BasicAdmin]☺ Error loading database. ![image](https://private-user-images.githubusercontent.com/31591836/292675511-92ded952-68e4-490e-a0c7-fa5c43029c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzYwMjgsIm5iZiI6MTcwMzQzNTcyOCwicGF0aCI6Ii8zMTU5MTgzNi8yOTI2NzU1MTEtOTJkZWQ5NTItNjhlNC00OTBlLWEwYzctZmE1YzQzMDI5YzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE2MzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYjZkYzI0MmE2Y2Y4MTNmZGVjNWNjZDBjMDU3N2Q5ODhjMDMxMjdhNDE4Nzc2YWY5OTRmYWUzZDNmMDgwNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyA2m2KZqkmXU_aOzLmP32i3WA8XUBvPh8sgyy8Corg)

A database is required, so you can use !ban/!gag/!mute.

**Comment by Hackmastr** [comment]
Pushed a fix to the shooting issue.

**Comment by denrio157** [comment]
> Mendorong perbaikan pada masalah pengambilan gambar.

So? another command cant work for right now? : /

**Comment by Hackmastr** [comment]
I'm sorry I can't read what you quoted.

**Comment by denrio157** [comment]
> I'm sorry I can't read what you quoted.

![image](https://github.com/Hackmastr/css-basic-admin/assets/31591836/feb3703a-8c8a-4519-a4cc-413ffdc4ab20)
