### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by Scentedsoap1314** [Hackmastr/css-basic-admin#13]
I can only kick en name's player，cn name display not found

**Comment by Hackmastr** [comment]
Hello,

I'll take a look. Thanks!

**Comment by Scentedsoap1314** [comment]
Please as soon fix  plugin，Currently  no plugins  can kick  chinese name's players,I really need this nice plugin,thank you

**Comment by Hackmastr** [comment]
Hello,

Please put the name between quotes (e.g.: !slap "测试"). 
I am afraid I can't fix targeting players with such names because of the way CSS handles them.

Alternatively, you can use player ids (e.g.: !slap #66555).

**Comment by Scentedsoap1314** [comment]
Use id can  normal kick  player.
Can CSS commands be added to overload admin.json,Thanks

**Comment by Hackmastr** [comment]
Hello,

Yes, please read: https://docs.cssharp.dev/docs/admin-framework/defining-command-overrides.html

Thanks.
