### ISSUE TITLE
HOW TO ADD ADMINS 

### ISSUE THREAD

**Issue by mayersgamer** [Hackmastr/css-basic-admin#14]
![Screenshot 2024-01-06 180950](https://github.com/Hackmastr/css-basic-admin/assets/5068539/90e67b67-27f1-4e33-a46f-942351e0b352)

THIS 2 steam id i want to add as admins give me an example 
STEAM_0:1:68620657
STEAM_0:1:795510228

**Comment by Hackmastr** [comment]
Hi,

Please read: https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

It has clear steps on how to add admins.

**Comment by mayersgamer** [comment]
already read that i want an example from you , everytime i add second admin , the first admin lose his admin rights and server write you have not @generic to do this ...

**Comment by Hackmastr** [comment]
> already read that i want an example from you , everytime i add second admin , the first admin lose his admin rights and server write you have not @Generic to do this ...

Sure. Please share your config here.

**Comment by mayersgamer** [comment]
{
  "admin1": {
    "identity": "STEAM_0:0:795510228",
    "flags": ["@css/changemap", "@css/generic"]
  },
  "admin2": {
    "identity": "STEAM_0:1:68620657",
    "flags": ["@css/root"]
  }
}

**Comment by Hackmastr** [comment]
Your config. seems OK.

Try using Steamid64 instead.
