### ISSUE TITLE
Adding more tags

### ISSUE THREAD

**Issue by PorcusorulMagic** [Hackmastr/css-basic-admin#2]
Hello! Can you add more tags for each flag (like, we can customize our tag for any flag)

**Comment by crashzk** [comment]
Doubt, why not leave a tag system for specific plugins for this? Leave just basic admin commands and such, focus on that and so on;

**Comment by Hackmastr** [comment]
> Doubt, why not leave a tag system for specific plugins for this? Leave just basic admin commands and such, focus on that and so on;

I imagine it's for stuff like admin chat (!say, and the like). 
Not a priority, but I'll do it until a good chat processor is out.
Thanks :).
