### ISSUE TITLE
[REQ] Freeze command support

### ISSUE THREAD

**Issue by crashzk** [Hackmastr/css-basic-admin#6]
Would it be possible to implement support for the `!freeze` command?

It would have the same function as `!bury`, the difference is that in addition to freezing the player, it only stays like that for a certain second and then can walk normally again.

I believe that even an improvement to the `!bury` command could be, adding an option to send a time in X seconds along with the command, for example; `!bury crashzk 15` so he doesn't move for just 15 seconds, if he leaves it without time it only comes out if he dies or if you use the `!unbury` command.

**Comment by chycken** [comment]
same with !hp

**Comment by Hackmastr** [comment]
Added with https://github.com/Hackmastr/css-basic-admin/commit/9e553a796d549b7cc4a325fe6349a77086105133

Thanks!
