### ISSUE TITLE
added plugin to my server and it crashes

### ISSUE THREAD

**Issue by Ganji89420** [Hackmastr/css-basic-admin#8]
This plugin is causing server crash with this error code.

![image](https://github.com/Hackmastr/css-basic-admin/assets/151049632/d43b5081-fbe0-4bbd-b94e-c4f2bfa3cb8f)

**Comment by Hackmastr** [comment]
Hello,

Please try the [latest release](https://github.com/Hackmastr/css-basic-admin/releases/tag/ac5d3f0).

Thanks.
