### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chycken** [Hackmastr/css-basic-admin#9]
Hello,
as you know, daffy made a cs2-simpleadmin system that is based on your basic admin system.
It would be great if the two of you teamed up and developed a well-functioning admin system together, because for example daffy has already done quite a lot in his own, and everyone just wants an admin system that works well.
You should talk each other. 👯 
This is his plugin: https://github.com/daffyyyy/CS2-SimpleAdmin

**Comment by Hackmastr** [comment]
Hi, 

Done with [9b12f55](https://github.com/Hackmastr/css-basic-admin/releases/tag/9b12f55).

Thanks!
